Environment = "local"
LogLevel = "debug"

DBUrl = "postgres://user:mypassword@db:5432/user?sslmode=disable"
TokenSymmetricKey = "12345678901234567890123456789012"
AccessTokenDuration = "15m"
RefreshTokenDuration = "24h"
