version: '3.4'

services:
  app:
    build:
      context: .
      target: local
    depends_on:
      - db
    environment:
      APPENV: ${APPENV:-local-appenv}
      PORT: 5000
      SB_PROCESS: ${SB_PROCESS:-main}
      SB_PROJECT: simplebank
      VERSION: 0.0.0
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - ~/.cache:/root/.cache
      - ~/go/pkg/mod:/root/go/pkg/mod
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5555:5432"

volumes:
  dbdata:
  redis_data:
    driver: local
